#ifndef CALIBRATIONRESULTS_H
#define CALIBRATIONRESULTS_H

#include <QDialog>
#include <tobii/sdk/cpp/EyeTracker.hpp>

namespace tetio = tobii::sdk::cpp;

namespace Ui {
//This class will be generated by Qt
class CalibrationResults;
}

//Class for visualization of the calibration results.
class CalibrationResults : public QDialog
{
    Q_OBJECT
    
public:
    explicit CalibrationResults(QWidget *parent = 0);
    ~CalibrationResults();

	void setPlotData(tetio::Calibration::pointer_t calibrationData);

private:
    Ui::CalibrationResults *ui;
};

#endif // CALIBRATIONRESULTS_H
