#ifndef FRAMERATEDIALOG_H
#define FRAMERATEDIALOG_H

#include <QDialog>

namespace Ui {
//This class will be generated by Qt
class FrameRateDialog;
}

//UI for change eyetracker's framerate
class FrameRateDialog : public QDialog
{
    Q_OBJECT
    
public:
    explicit FrameRateDialog(QWidget *parent = 0);
    ~FrameRateDialog();

    bool execute(QWidget *parent, const QVector<float> &availableframerates, float framerate);
    float getSelectedFrameRate();

private:
    void initFrameRatesComboBox(const QVector<float> &availableframerates, float framerate);
    Ui::FrameRateDialog *m_ui;
};

#endif // FRAMERATEDIALOG_H
